# Generated by Django 5.0.6 on 2024-05-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('descript', models.TextField()),
                ('path', models.ImageField(upload_to='imagens/')),
            ],
        ),
    ]
